name: yap

on:
  push:
    branches:
      - master
    tags:
      - release

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: test and publish
      run: |
        npm install -g nyc mocha typescript ts-node
        npm ci
        npm run lint
        npm run test:integration
        npm run coverage
        npm run build
        echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" >> ~/.npmrc
        npm publish --access public
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
