name: Node CI

on:
  push:
    branches:
      - master
    tags:
      - release

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: test and publish
      run: |
        npm ci
        npm test
        npm run build
        echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" >> ~/.npmrc
        cd dist
        npm publish --new-version ${GITHUB_REF#"refs/tags/"} --no-git-tag-version
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
